export enum ActionsTypes {
  ADD_SAUNTER = "ADD_SAUNTER",
  REMOVE_SAUNTER = "REMOVE_SAUNTER",
  ADD_TO_FAVORITES_SAUNTER = "ADD_TO_FAVORITES_SAUNTER",
  SELECT_SAUNTER = "SELECT_SAUNTER",
  INIT_SAUNTER_LIST = "INIT_SAUNTER_LIST", 
}